package com.workintech.Enum;

public enum BookCategories {

    ADVENTURE_STORIES,
    CLASSICS,
    CRIME,
    FAIRY_TALES_FABLES_AND_FOLK_TALES,
    FANTASY,
    HISTORICAL_FICTION,
    WAR,
    WOMENS_FICTION,
    YOUNG_ADULT,
    AUTOBIOGRAPHY_AND_MEMOIR,
    BIOGRAPHY,
    ESSAYS,
    NON_FICTION_NOVEL,
    SELF_HELP,
    HORROR,
    HUMOUR_AND_SATIRE,
    LITERARY_FICTION,
    MYSTERY,
    POETRY,
    PLAYS,
    ROMANCE,
    SCIENCE_FICTION,
    SHORT_STORIES,
    THRILLERS;
}
